### ISSUE TITLE
请问如何调整折线图位置？

### ISSUE THREAD

**Issue by Desgard** [WSeniOS/SNChartView#1]
x设置了7个坐标点后，在ip6的屏幕上就需要水平滑动才能浏览全图。控件初始化initWithFrame:CGRectMake(0, 200, self.view.frame.size.width, self.view.frame.size.height - 100)，在屏幕左边会有很大的空白部分，请问如何相左调整位置？

**Comment by WSenOS** [comment]
SNChartBar.h      static const CGFloat chartBarStartX = 80.f;

SNChartLine.h   static const CGFloat chartLineStartX = 80.f;   我这里设置的都是图标距左边80  留的这个空隙可以显示y轴的数字  你可以调小点

**Comment by Desgard** [comment]
ok，感谢。已经解决！
